# Built with Jekyll 2.5.3
#
# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: none

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Setup
title:               mini lazarillo
tagline:             'Una edición mínima del <i>Lazarillo de Tormes</i>'
description:         'Una edición mínima del <i>Lazarillo de Tormes</i> creada por estudiantes de Columbia University'
url:                 http://minilazarillo.github.io
baseurl:             ''
shareimg:            /public/img.jpg

# About/contact
author:
  name:              Mini Lazarillo Team
  url:
  email:

# Sass
sass:
  style: compressed
  sass_dir: _sass

# Custom vars
version:             0.0.3

# Gems
gems: ['jekyll/scholar']

# Scholar
scholar:
  style: modern-language-association
  locale: en

  sort_by: none
  order: ascending

  group_by: none
  group_order: ascending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: "{{reference}}"
  relative: "/ed/bibliography.html"

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: false

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
