# Built with Jekyll 2.5.3
#
# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: none

# Markdown specs
markdown: kramdown

# Collections
collections:
  texts:
    output: true

# Kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Setup
title:               mini lazarillo
tagline:             'edición mínima del <i>Lazarillo de Tormes</i>'
description:         'Edición mínima del <i>Lazarillo de Tormes</i> creada por estudiantes de Columbia University'
url:                 http://minilazarillo.github.io
baseurl:             ''
shareimg:            /public/img.jpg

# About/contact
author:
  name:              Mini Lazarillo Team

# Sass
sass:
  style: compressed
  sass_dir: _sass